# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 358fde630768925838effadc115a570fa2c3fd26c5714765215a4a7dd61e84be41933a4bef04fa63473cdc2a08ba59ceb3682f922979ea26dcfd4d38c74284bf
  twilio_number:  +16504168961

test:
  secret_key_base: 2a241bd38729d0b459c5a5b846b50d26fcd4060796d083a4759c50aa46548d343a87a4441ba45ee5ca77b30a1d994b584180bb2f0908ea0811297e91cfcfd013
  twilio_number:  +16504168961
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>